package com.firefliesdev.qrcode_example

import android.os.Bundle

import io.flutter.app.FlutterActivity
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugins.GeneratedPluginRegistrant

import android.R.attr.path
import java.io.File;

import androidx.core.content.FileProvider
import android.content.Intent
import android.icu.lang.UCharacter.GraphemeClusterBreak.T
import android.net.Uri
import android.icu.lang.UCharacter.GraphemeClusterBreak.T

import android.graphics.BitmapFactory
import android.os.Environment
import java.io.FileOutputStream
import android.graphics.Bitmap
import android.os.Build
import android.content.pm.PackageManager

class MainActivity: FlutterActivity() {
  //
  private val CHANNEL = "flutter.native/share"

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)

    //
    MethodChannel(flutterView, CHANNEL).setMethodCallHandler { call, result ->
      if(call.method == "shareImage") {
        shareImage(call.argument<String>("path")!!)
      }
    }
  }

  private fun shareImage(path :String) {
    val imageFile = File(applicationContext.cacheDir, path)
    val contentUri = FileProvider.getUriForFile(this, "com.firefliesdev.qrcode_example", imageFile)
    val intent = Intent(Intent.ACTION_SEND)

    intent.type = "image/*"
    intent.putExtra(Intent.EXTRA_STREAM, contentUri)
    intent.putExtra(Intent.EXTRA_TEXT, "QR Code generated by FirefliesDev")
    startActivity(Intent.createChooser(intent, "Share QR Code"))
  }
}
